version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - qdrant
      - mongodb
    env_file:
      - .env
    
    networks:
      - app_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    networks:
      - app_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # crawl4ai:
  #   image: unclecode/crawl4ai:basic-amd64
  #   ports:
  #     - "11235:11235"
  #   environment:
  #     - MAX_CONCURRENT_TASKS=5
  #     - CRAWL4AI_API_TOKEN=mytoken123
  #   networks:
  #     - app_network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - api
    networks:
      - app_network

  crawler:
    build:
      context: .
      dockerfile: docker/crawler.Dockerfile
    ports:
      - "11235:11235"
    volumes:
      - ./backend/crawler:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - app_network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      - mongodb
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
